export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const DELETE_USER = 'DELETED_USER';
export const DELETED_USER_SUCCESS = 'DELETED_USER_SUCCESS';

export const UPDATE_USER = 'UPDATED_USER';
export const UPDATED_USER_SUCCESS = 'UPDATED_USER_SUCCESS';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER';